import { Geist, Geist_Mono,Inter } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/src/components/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter ({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata = {
  title: "Aminpass",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en"  >
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
        <ToastProvider>
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
